name: Matrix Build
on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MYVAR: "Hello, World!"
    strategy:
      matrix:
        python: [3.9, 3.12, 3.11]
        person: [nathan, moshe]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: show var
        run: |
          echo ${{ env.MYVAR }}
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Print data
        run: |
          python --version
          echo ${{ matrix.person }
          
